trigger:
- master
pr:
- master

jobs:
- job: windows
  displayName: 'Windows'
  pool:
    vmImage: 'windows-2019'

  strategy:
    matrix:
      Win32-Release:
        buildPlatform: Win32
        buildConfiguration: Release
      Win32-Debug:
        buildPlatform: Win32
        buildConfiguration: Debug
      x64-Release:
        buildPlatform: x64
        buildConfiguration: Release
      x64-Debug:
        buildPlatform: x64
        buildConfiguration: Debug

  workspace:
    clean: all

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    submodules: recursive
    
  - task: CMake@1
    inputs:
      workingDirectory: 'build_$(buildPlatform)_$(buildConfiguration)'
      cmakeArgs: '-A "$(buildPlatform)" -DCMAKE_BUILD_TYPE=$(buildConfiguration) -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX=./install -DBGFX_BUILD_EXAMPLES=OFF -DBGFX_BUILD_TOOLS=ON -DBGFX_INSTALL=ON ..'

  - task: CMake@1
    inputs:
      workingDirectory: 'build_$(buildPlatform)_$(buildConfiguration)'
      cmakeArgs: '--build . --target install --config $(buildConfiguration)'